# Generated by Django 5.2.6 on 2025-10-02 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='badge_icons/')),
                ('criteria', models.JSONField(blank=True, help_text="e.g., {type: 'modules_completed', count: 3}", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='interactive_payload',
            field=models.JSONField(blank=True, help_text='JSON config for interactive content (e.g., sorting items and bins)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='interactive_type',
            field=models.CharField(choices=[('none', 'None'), ('sorting', 'Sorting Game')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='external_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='hierarchy_stage',
            field=models.CharField(blank=True, choices=[('reduce', 'Reduce'), ('reuse', 'Reuse'), ('recycle', 'Recycle'), ('recover', 'Recover'), ('dispose', 'Dispose')], max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='waste_stream',
            field=models.CharField(blank=True, choices=[('solid', 'Solid Waste'), ('hazardous', 'Hazardous Waste'), ('e_waste', 'E-Waste'), ('organic', 'Organic Waste'), ('cnd', 'Construction & Demolition')], max_length=20),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('for_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearning.role')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='target_roles',
            field=models.ManyToManyField(blank=True, related_name='modules', to='elearning.role'),
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PathModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.module')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_modules', to='elearning.learningpath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('path', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
