# Generated by Django 5.2.6 on 2025-10-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_tag_alter_category_options_badge_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='elearning.category'),
        ),
    ]
