# Generated by Django 5.2.6 on 2025-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_module_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
