# Generated by Django 5.2.6 on 2025-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_category_icon_class_lessonprogress_last_accessed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#10B981', max_length=7),
        ),
    ]
