# Generated by Django 5.2.6 on 2025-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_tag_name_bem_tag_name_ny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_file_bem',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audio/bem/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio_file_ny',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audio/ny/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_bem',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/bem/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_ny',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/ny/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audio/en/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/en/'),
        ),
    ]
