# Generated by Django 5.1.1 on 2025-11-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_add_pdf_guide'),
        ('elearning', '0010_lesson_audio_file_bem_lesson_audio_file_ny_and_more'),
    ]

    operations = [
    ]
