# Generated by Django 5.1.1 on 2025-12-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_optimize_performance'),
        ('elearning', '0011_merge_20251125_1132'),
    ]

    operations = [
    ]
