# Generated by Django 5.1.1 on 2025-12-15 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_merge_20251214_2117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pdf_guide',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file_bem',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file_ny',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('quiz', 'Quiz')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file_bem',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file_ny',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='enrollments_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='elearning_c_is_acti_7efd86_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='elearning_c_created_5fb98f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='elearning_l_module__4785fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'is_published'], name='elearning_l_module__cec9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_preview', 'is_published'], name='elearning_l_is_prev_8bfbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['created_at'], name='elearning_l_created_549e76_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_published', 'is_active'], name='elearning_m_is_publ_c7f51a_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['category', 'is_published'], name='elearning_m_categor_2c7cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['difficulty', 'is_published'], name='elearning_m_difficu_302ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_featured', 'enrollments_count'], name='elearning_m_is_feat_dcf8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['created_at'], name='elearning_m_created_584fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['title'], name='elearning_m_title_5cd78b_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['average_rating', 'enrollments_count'], name='elearning_m_average_ff7603_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='elearning_t_name_3debeb_idx'),
        ),
    ]
