# Generated by Django 5.2.6 on 2025-11-16 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('cleanup', 'Cleanup Challenge'), ('recycling', 'Recycling Challenge'), ('education', 'Education Challenge'), ('reporting', 'Reporting Challenge')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_goal', models.IntegerField(help_text='Target number (e.g., 100 reports, 50kg waste)')),
                ('current_progress', models.IntegerField(default=0)),
                ('reward_points', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='challenges/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('new_event', 'New Event'), ('forum_reply', 'Forum Reply'), ('story_approved', 'Story Approved'), ('achievement', 'Achievement Unlocked'), ('health_alert', 'Health Alert'), ('emergency', 'Emergency Alert')], max_length=20),
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('cholera', 'Cholera Outbreak'), ('flooding', 'Flooding'), ('hazardous_waste', 'Hazardous Waste'), ('water_contamination', 'Water Contamination')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_areas', models.TextField(help_text='Comma-separated list of affected areas')),
                ('hygiene_tips', models.TextField()),
                ('nearest_clinics', models.TextField(help_text='List of nearest clinics with addresses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.communitychallenge')),
            ],
            options={
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
