# Generated by Django 5.2.6 on 2025-11-17 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_challengeparticipant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevent',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='healthalert',
            options={'ordering': ['-severity', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='forumreply',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='contribution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitychallenge',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='communitychallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/'),
        ),
        migrations.AlterField(
            model_name='communitychallenge',
            name='reward_points',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='communitychallenge',
            name='target_goal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='event_type',
            field=models.CharField(choices=[('cleanup', 'Community Cleanup'), ('workshop', 'Educational Workshop'), ('campaign', 'Awareness Campaign'), ('competition', 'Eco Competition')], default='cleanup', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='attended',
            field=models.BooleanField(default=False, help_text='Did the user attend?'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='community.communityevent'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description_bem',
            field=models.TextField(blank=True, verbose_name='Description (Bemba)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description_ny',
            field=models.TextField(blank=True, verbose_name='Description (Nyanja)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(default='comments', help_text='FontAwesome class e.g. fa-comments', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name (English)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name_bem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Bemba)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name_ny',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Nyanja)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='is_solution',
            field=models.BooleanField(default=False, help_text='Mark as accepted solution'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Lock topic (no new replies)'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pin to top'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='affected_areas',
            field=models.TextField(help_text='Comma-separated list'),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='alert_type',
            field=models.CharField(choices=[('cholera', 'Cholera Outbreak'), ('flooding', 'Flooding'), ('hazardous_waste', 'Hazardous Waste'), ('water_contamination', 'Water Contamination'), ('air_pollution', 'Air Pollution'), ('disease', 'Disease Outbreak')], max_length=30),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='nearest_clinics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='healthalert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('new_event', 'New Event'), ('forum_reply', 'Forum Reply'), ('story_approved', 'Story Approved'), ('achievement', 'Achievement Unlocked'), ('health_alert', 'Health Alert'), ('emergency', 'Emergency Alert'), ('challenge_update', 'Challenge Update')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialmediashare',
            name='content_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='socialmediashare',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('copy', 'Copy Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Requires admin approval'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge', 'user'], name='community_c_challen_08dd33_idx'),
        ),
        migrations.AddIndex(
            model_name='communitychallenge',
            index=models.Index(fields=['is_active', 'end_date'], name='community_c_is_acti_dc6509_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['start_date'], name='community_c_start_d_d286cf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='community_e_event_i_3b6dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='forumcategory',
            index=models.Index(fields=['order'], name='community_f_order_133eac_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['-created_at'], name='community_f_created_19f840_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['-created_at'], name='community_f_created_703c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['-is_pinned', '-updated_at'], name='community_f_is_pinn_d92239_idx'),
        ),
        migrations.AddIndex(
            model_name='healthalert',
            index=models.Index(fields=['is_active', '-created_at'], name='community_h_is_acti_0cd0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at', 'is_read'], name='community_n_created_92cbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediashare',
            index=models.Index(fields=['-shared_at'], name='community_s_shared__c947e8_idx'),
        ),
        migrations.AddIndex(
            model_name='successstory',
            index=models.Index(fields=['-created_at'], name='community_s_created_8b5551_idx'),
        ),
    ]
