# Generated by Django 5.1.1 on 2025-12-11 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_add_challenge_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('interest_level', models.CharField(choices=[('join', 'Will Join'), ('interested', 'Interested'), ('maybe', 'Maybe')], default='join', max_length=20)),
                ('attended', models.BooleanField(default=False, help_text='Did the user attend?')),
                ('attendance_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3days_sent', models.BooleanField(default=False)),
                ('reminder_1day_sent', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campaign Participant',
                'verbose_name_plural': 'Campaign Participants',
            },
        ),
        migrations.CreateModel(
            name='CommunityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Campaign Title')),
                ('title_bem', models.CharField(blank=True, max_length=200, verbose_name='Title (Bemba)')),
                ('title_ny', models.CharField(blank=True, max_length=200, verbose_name='Title (Nyanja)')),
                ('description', models.TextField(verbose_name='Campaign Description')),
                ('description_bem', models.TextField(blank=True, verbose_name='Description (Bemba)')),
                ('description_ny', models.TextField(blank=True, verbose_name='Description (Nyanja)')),
                ('campaign_type', models.CharField(choices=[('cleanup', 'Community Cleanup'), ('workshop', 'Segregation Workshop'), ('challenge', 'Zero-Plastic Challenge'), ('education', 'Waste Management Education'), ('recycling', 'Recycling Drive'), ('composting', 'Composting Workshop')], default='cleanup', max_length=20)),
                ('location', models.CharField(max_length=255, verbose_name='Campaign Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_date', models.DateTimeField(verbose_name='End Date & Time')),
                ('recurrence', models.CharField(choices=[('one_time', 'One-time Event'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one_time', max_length=20)),
                ('next_occurrence', models.DateTimeField(blank=True, help_text='Auto-calculated next occurrence', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Participants')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Campaign')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published (visible to users)')),
                ('participant_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Campaign',
                'verbose_name_plural': 'Community Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='challengeparticipant',
            name='community_c_challen_08dd33_idx',
        ),
        migrations.RenameIndex(
            model_name='challengeparticipant',
            new_name='community_c_challen_a4b35f_idx',
            old_name='community_c_challen_8e7c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='challengeproof',
            new_name='community_c_status_a5d331_idx',
            old_name='community_c_status_9a2b3c_idx',
        ),
        migrations.AddField(
            model_name='campaignparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycampaign',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignparticipant',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community.communitycampaign'),
        ),
        migrations.AddIndex(
            model_name='communitycampaign',
            index=models.Index(fields=['start_date'], name='community_c_start_d_eac576_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycampaign',
            index=models.Index(fields=['is_active', 'is_published'], name='community_c_is_acti_1f766c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignparticipant',
            index=models.Index(fields=['campaign', 'user'], name='community_c_campaig_d99dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignparticipant',
            index=models.Index(fields=['registered_at'], name='community_c_registe_60200d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipant',
            unique_together={('campaign', 'user')},
        ),
    ]
