# Generated by Django 5.1.1 on 2025-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_campaignparticipant_communitycampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeproof',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='challengeproof',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='communitycampaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='communitychallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
