# Generated by Django 5.2.6 on 2025-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken. Please choose another.'}, help_text='Enter any username you like - no character restrictions', max_length=150, unique=True),
        ),
    ]
