# Generated by Django 5.1.1 on 2025-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('super_admin', 'Super Administrator')], default='student', max_length=20),
        ),
    ]
