# Generated by Django 5.2.6 on 2025-11-23 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive SMS notifications', verbose_name='SMS Notifications')),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Receive WhatsApp notifications', verbose_name='WhatsApp Notifications')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='Email Notifications')),
                ('event_reminders', models.BooleanField(default=True, help_text='Get notified about upcoming events', verbose_name='Event Reminders')),
                ('challenge_updates', models.BooleanField(default=True, help_text='Receive updates on your challenge progress', verbose_name='Challenge Updates')),
                ('forum_replies', models.BooleanField(default=True, help_text='Get notified when someone replies to your posts', verbose_name='Forum Replies')),
                ('reward_updates', models.BooleanField(default=True, help_text='Receive updates on reward redemptions', verbose_name='Reward Updates')),
                ('community_news', models.BooleanField(default=True, help_text='Get updates about community activities', verbose_name='Community News')),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Summary')], default='instant', max_length=10, verbose_name='Notification Frequency')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='No notifications during quiet hours (e.g., 22:00)', null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Resume notifications after quiet hours (e.g., 07:00)', null=True, verbose_name='Quiet Hours End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
