# Generated by Django 5.2.6 on 2025-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('custom', 'Custom')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
