# Generated by Django 5.1.1 on 2025-12-10 21:10

from django.db import migrations


def cleanup_social_accounts(apps, schema_editor):
    """
    Clean up any existing social account data
    """
    try:
        # Try to get social account models if they exist
        SocialAccount = apps.get_model('socialaccount', 'SocialAccount')
        SocialToken = apps.get_model('socialaccount', 'SocialToken')
        SocialApp = apps.get_model('socialaccount', 'SocialApp')
        
        # Delete all social accounts, tokens, and apps
        SocialAccount.objects.all().delete()
        SocialToken.objects.all().delete() 
        SocialApp.objects.all().delete()
        
        print("✅ Cleaned up social account data")
    except Exception as e:
        # If socialaccount app is not installed, this is expected
        print(f"ℹ️  Social account cleanup skipped: {e}")


def reverse_cleanup_social_accounts(apps, schema_editor):
    """
    Reverse operation - nothing to do
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_gender'),
    ]

    operations = [
        migrations.RunPython(cleanup_social_accounts, reverse_cleanup_social_accounts),
    ]
