# Generated by Django 5.1.1 on 2025-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_add_default_authorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpingreport',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dumpingreport',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dumpingreport',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
