# Generated by Django 5.2.6 on 2025-11-16 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_bem', models.CharField(blank=True, max_length=200)),
                ('title_ny', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_bem', models.TextField(blank=True)),
                ('description_ny', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('individual', 'Individual Challenge'), ('community', 'Community Challenge'), ('district', 'District Challenge')], max_length=20)),
                ('points_reward', models.IntegerField(default=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_metric', models.CharField(max_length=100)),
                ('target_value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('total_reports', models.IntegerField(default=0)),
                ('resolved_reports', models.IntegerField(default=0)),
                ('tons_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dumps_cleaned', models.IntegerField(default=0)),
                ('active_members', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community Impact Metrics',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_bem', models.CharField(blank=True, max_length=200)),
                ('name_ny', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('airtime', 'Airtime Voucher'), ('certificate', 'Recognition Certificate'), ('badge', 'Digital Badge'), ('merchandise', 'Eco Merchandise')], max_length=20)),
                ('points_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='rewards/')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('module_complete', 'Module Completed'), ('quiz_pass', 'Quiz Passed'), ('report_submit', 'Report Submitted'), ('event_attend', 'Event Attended'), ('story_share', 'Story Shared'), ('forum_post', 'Forum Post'), ('daily_login', 'Daily Login'), ('challenge_complete', 'Challenge Completed'), ('redemption', 'Points Redeemed')], max_length=30)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redemption_code', models.CharField(max_length=50, unique=True)),
                ('contact_info', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('available_points', models.IntegerField(default=0)),
                ('redeemed_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Points',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
